/**
 * 统一业务错误码。
 * 客户端可直接用 message 展示中文提示。
 */
export const ErrorCode = {
  UNKNOWN: "UNKNOWN",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",

  AUTH_EMAIL_TAKEN: "AUTH_EMAIL_TAKEN",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_REFRESH_REVOKED: "AUTH_REFRESH_REVOKED",

  ENTITLEMENT_HOST_LIMIT: "ENTITLEMENT_HOST_LIMIT",
  ENTITLEMENT_SYNC_DISABLED: "ENTITLEMENT_SYNC_DISABLED",
  ENTITLEMENT_DEVICE_LIMIT: "ENTITLEMENT_DEVICE_LIMIT",

  HOST_INVALID_PORT: "HOST_INVALID_PORT",
  HOST_REQUIRED_FIELD: "HOST_REQUIRED_FIELD",

  BACKUP_BAD_PASSWORD: "BACKUP_BAD_PASSWORD",
  BACKUP_INVALID_FORMAT: "BACKUP_INVALID_FORMAT",

  IMPORT_UNSUPPORTED: "IMPORT_UNSUPPORTED",
  IMPORT_PARSE_FAILED: "IMPORT_PARSE_FAILED",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

/**
 * API 统一错误响应体。
 */
export interface ApiErrorBody {
  code: ErrorCodeValue | string;
  message: string;
  details?: unknown;
}
